### ISSUE TITLE
UI resolution

### ISSUE THREAD

**Issue by hsshss2005** [Helfima/DSP_Mods#1]
hey， Can I modify the UI resolution, the font is very small under 4k

**Comment by Helfima** [comment]
hello, actually you don't but i found how do that
if you can try the version in zip
[DSP_Helmod.1.3.0.zip](https://github.com/Helfima/DSP_Mods/files/6065322/DSP_Helmod.1.3.0.zip)

probably I need add a tool to ajuste size, say me it's too big
