### ISSUE TITLE
Error on loading save

### ISSUE THREAD

**Issue by TimeDrawsNigh** [Helfima/DSP_Mods#3]
Saw your mod and installed (vers: 1.4.1), after loading my save file I got the error seen in the attached image.

**Comment by TimeDrawsNigh** [comment]
![20210314234004_1](https://user-images.githubusercontent.com/13444849/111101052-78acc100-851f-11eb-9323-c942177edec2.jpg)

**Comment by Helfima** [comment]
fixed in v1.4.2

**Comment by TimeDrawsNigh** [comment]
Thanks! It's working now. :)
