### ISSUE TITLE
Wrong UI scaling (ultrawide)

### ISSUE THREAD

**Issue by Razunter** [Helfima/DSP_Mods#5]
UI gets too stretched on 3440x1440 resolution:
![bug](https://user-images.githubusercontent.com/362900/114012741-c6df8680-9877-11eb-8956-50a53e831642.png)

**Comment by lictw** [comment]
+1
![image](https://user-images.githubusercontent.com/11904484/114459114-c84adf00-9be8-11eb-9c9f-6243f3559111.png)

**Comment by Helfima** [comment]
fixed in v1.4.4
